---
# common/tasks/main.yml: Main tasks for common role
#
# We created the common role to run on every one of our Debian/Ubuntu systems to
# provide a consistent environment that includes:
#
# - Unintended upgrades: Automated system security updates
# - Firewall input restricted to IPv4 tcp port 22 by default
# - Etckeeper: Revision control for the entire /etc directory
# - SSHd hardening
# - Hostname and hosts file configuration
# - Common system software packages
# - Provides handlers that are imported from other roles
#
# The common role is required for the Icinga master instance(s) e.g. due to the
# dependency of the Icinga master to have a firewall installed on the system. The
# common role is optional for the satellite instances.

- name: Include {{ ansible_distribution }} specific vars
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}_{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags: vars

- name: Set the system hostname
  hostname: name={{ inventory_hostname_short }}

- name: Configure system hosts file
  lineinfile: dest=/etc/hosts
              regexp="^127\.0\.0\.1"
              line='127.0.0.1 {{inventory_hostname}} {{inventory_hostname_short}} localhost'
              owner=root group=root mode=0644
  async: 15
  poll: 0

- name: Configure sshd to disable password authentication
  lineinfile: dest=/etc/ssh/sshd_config
              regexp='^[#]?PasswordAuthentication'
              line='PasswordAuthentication no'
              owner=root group=root mode=0644
  async: 15
  poll: 0
  tags: ssh-rekey

- name: Configure sshd to disable challenge authentication
  lineinfile: dest=/etc/ssh/sshd_config
              regexp='^[#]?ChallengeResponseAuthentication'
              line='ChallengeResponseAuthentication no'
              owner=root group=root mode=0644
  async: 15
  poll: 0
  tags: ssh-rekey

- name: Place admin ssh public keys in root authorized_keys
  authorized_key: user=root exclusive=True key={{ ssh_root_user_public_keys | join('\n') }}
  notify: sshd
  tags: ssh-rekey
  ignore_errors: true

- name: Enable EPEL on RedHat
  package: name=epel-release state=installed
  when: ansible_os_family == "RedHat"

- name: Install Common Packages
  environment:
    DEBIAN_FRONTEND: noninteractive
  package: name={{ item }}
  with_items: "{{ common_packages }}"


- name: Configure etckeeper
  action: template src=etckeeper.conf.j2 dest=/etc/etckeeper/etckeeper.conf

- name: Create gitconfig for root user so that etckeeper can commit
  template: src=gitconfig.j2 dest=/root/.gitconfig

- name: Make etckeeper initial commit if not already initialized
  command: /usr/bin/etckeeper init
  ignore_errors: yes

  # At the moment, only Ubuntu will receive unattended upgrades, not CentOS or Debian
- name: Enable Unattended Upgrades
  template: src=unattended_upgrades.conf.j2 dest=/etc/apt/apt.conf.d/10periodic
  when: ansible_distribution == 'Ubuntu'

- name: Copy firewalld python 2 bindings package to remote
  copy: src=python-firewalld_0.1-0.deb
        dest=/tmp/python-firewalld_0.1-0.deb
        owner=root
        group=root
        mode=600
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '16.04'

- name: Install firewalld python 2 bindings on Ubuntu 16.04
  apt: deb=/tmp/python-firewalld_0.1-0.deb
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '16.04'

- name: Ensure that firewalld is running
  service: name=firewalld state=started enabled=yes

# Ensures that all handlers are triggered
- meta: flush_handlers
