---
# Include distro- and os_family- specific vars
# hierarchically 

- name: Include {{ ansible_distribution }}_{{ ansible_distribution_major_version }} specific vars
  include_vars: "{{ ansible_distribution }}_{{ ansible_distribution_major_version }}.yml"

- name: Include {{ ansible_distribution }} specific vars
  include_vars: "{{ ansible_distribution }}.yml"
  ignore_errors: true
  
- name: Include {{ ansible_os_family }} specific vars
  include_vars: "{{ ansible_os_family }}.yml"
  ignore_errors: true

