---

- name: Include {{ ansible_os_family }} specific common packages
  include_vars: "../vars/{{ ansible_os_family }}.yml"

- name: Install postfix and bsd-mailx
  package: name={{ item }} state=installed
  with_items: "{{ packages }}"

- name: Ensure that postix directory exists
  file: dest=/etc/postfix
        state=directory

- name: Install postfix configuration
  template: src=main.cf.j2
            dest=/etc/postfix/main.cf
  notify:
    - restart postfix
